# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "recruiter"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT
session: "YAML"
session_dir: "../shared/dancer-sessions"

#template: "simple"
gh_client_id: "fa51807d54e215bb7bcc"
gh_secret: "0511d23714487e52041e8b241ddd46fe132c31d7"
gh_redirect: "http://recruiter.hisaju.org/ghregist"

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'

